services:
  spark-history:
    image: local/spark-events
    container_name: spark-history
    ports:
      - "18080:18080"
    volumes:
      - ./spark-events:/spark-events
    environment:
      - SPARK_HOME=/opt/spark
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      - PATH=$PATH:/opt/spark/bin
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge